# Generated by Django 3.1.2 on 2020-11-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDeposita', models.CharField(max_length=50)),
                ('nombreRecibe', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
    ]
